### ISSUE TITLE
500 error when trying to share a post

### ISSUE THREAD

**Issue by acw0** [inoda/journal#15]
Hi, I get a 500 "unexpected error" when trying to share a post, both public and secret.

Here is a pastebin of the error in my console: [https://mystb.in/dafafuzoka.coffeescript](https://mystb.in/dafafuzoka.coffeescript)

I'm running the latest version of journal in Docker, slightly modified since the hub's ruby 3.6 image now targets 3.6.6 instead of 3.6.5 (which is what the build script expects).

Please let me know if you need any more information from me. I'm not at all familiar with Ruby but I'd like to be as helpful as I can anyway :D

**Comment by inoda** [comment]
@acw0 Make sure you have these 2 ENV vars set up. I just sanity checked that sharing works locally and all seems well to me.

<img width="985" alt="Screen Shot 2020-05-09 at 8 47 45 PM" src="https://user-images.githubusercontent.com/7588174/81489727-5af33900-9236-11ea-956e-99f9e45d3f57.png">

**Comment by acw0** [comment]
Ah, that worked, thank you. 
I looked back at the installation docs and the `SHARING_TOKEN_CIPHER_IV` instructions seem to be missing from the Docker page, could they be added there?

**Comment by inoda** [comment]
Done!
