### ISSUE TITLE
Dockerfile ruby version

### ISSUE THREAD

**Issue by italodeandra** [inoda/journal#23]
The Gemfile uses ruby `2.6.6` but currently the Dockerfile fetches the `2.6.7`.

The fix is to change the version on the Dockerfile from `2.6` to `2.6.6`.

**Comment by inoda** [comment]
@italodeandra Bumped it here: https://github.com/inoda/journal/commit/3d3d427ae29f6ae4e3a4e1fc4d29d0da0ce1c8d7
