### ISSUE TITLE
Docker image 

### ISSUE THREAD

**Issue by alexkutsan** [inoda/journal#3]
Would be nice to have docker image for this app

**Comment by inoda** [comment]
@alexkutsan I have no experience with Docker but would accept a PR if you created a Dockerfile for this!

**Comment by alexkutsan** [comment]
I was trying to create Docker image, but I have no experience deploying node js applications :rofl:, faced with several issues. 
Could you please create some kind of steps how to run this application on clear ubuntu environment?

**Comment by inoda** [comment]
@alexkutsan This is a standard Rails app. I imagine there are some guides out there on running Rails on Ubuntu!

**Comment by inoda** [comment]
I unfortunately don't know how to get started on Ubuntu (I'm on a Mac), so I'd be starting from the same point you are.

**Comment by alexkutsan** [comment]
I am trying to setup this application.
Currently used following steps in docker file to setup environment: 

```
# gem update --system
# gem install bundler
# bundle update --bundler
# bundle install
```

the according to updated readme :

```
# bundle exec rails c 
Loading development environment (Rails 6.0.0)
irb(main):001:0> 
irb(main):002:0> User.create!(username: "alex", password: "password") 
Traceback (most recent call last):
        1: from (irb):2
PG::ConnectionBad (could not connect to server: No such file or directory)
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

Could you please tip me how to fix this issue?

**Comment by inoda** [comment]
@alexkutsan You need a postgresql db server running

**Comment by alexkutsan** [comment]
I create database host :-) 
My next error : 
```
root@56f247facea5:/myapp# User.create!(username: "alex", password: "password") 
bash: !: event not found
root@56f247facea5:/myapp# bundle exec rails c 
Loading development environment (Rails 6.0.0)
irb(main):001:0> User.create!(username: "alex", password: "password") 
Traceback (most recent call last):
        1: from (irb):1
ActiveRecord::NoDatabaseError (FATAL:  database "journal_development" does not exist)
irb(main):002:0> 

```

looks like I should precreate some database?

**Comment by alexkutsan** [comment]
Well, I googled, that I can create database with : 
```rake db:create ```

My next error : 
```root@56f247facea5:/myapp# bundle exec rails c 
Loading development environment (Rails 6.0.0)              
irb(main):001:0> User.create!(username: "alex", password: "password")                                                 
Traceback (most recent call last):                         
        1: from (irb):1                                    
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist)                          
LINE 8:  WHERE a.attrelid = '"users"'::regclass    
                            ^                         
```

**Comment by inoda** [comment]
You need to run rake db:migrate

**Comment by alexkutsan** [comment]
Oh, thanks! 
Sorry for so many questions.

Looks like user successfully created, but on localhost:3000 I have some errors: 

![Screenshot from 2019-12-03 21-54-08](https://user-images.githubusercontent.com/860357/70084712-7c148580-1617-11ea-925e-99c605f85fcd.png)

**Comment by alexkutsan** [comment]
And error after pressing migrate button : 

![Uploading Screenshot from 2019-12-03 21-55-05.png…]()

**Comment by alexkutsan** [comment]
And error after pressing migrate button : 

![Screenshot from 2019-12-03 21-55-05](https://user-images.githubusercontent.com/860357/70084816-b9791300-1617-11ea-91b3-d511612bfbe4.png)

**Comment by inoda** [comment]
you are missing ENV vars. see this about required ENV vars for encryption: https://github.com/inoda/journal/blob/master/docs/homebrew_install.md

**Comment by alexkutsan** [comment]
Thank you so much! Looks like successfully installed it and runned from docker. I will create Dockerfile, docker compose and instructions. 
![Screenshot from 2019-12-03 22-04-36](https://user-images.githubusercontent.com/860357/70085509-06a9b480-1619-11ea-879c-def6c2ebef4d.png)

**Comment by inoda** [comment]
@alexkutsan That's awesome news!! Thank you for taking the time to do this ⭐️

**Comment by koterpillar** [comment]
Sorry for stealing this, I've made a Dockerfile in #8 - @alexkutsan maybe we can collaborate there?
