### ISSUE TITLE
Docker Compose file?

### ISSUE THREAD

**Issue by wi0001** [inoda/journal#37]
Hey why is there no docker compose file.
This is how I usually always spool up my containers and there is none supplied.

Do you plan on adding one?

**Comment by wi0001** [comment]
Is this compose file functional, haven't had a chance to test it yet!
Thank you guys 🥇

**Comment by danielgraycode** [comment]
Hi, I had some issues with the docker-compose file, when trying to docker-compose up I got the following errors: 
```
Unsupported config option for networks: 'journal'
Unsupported config option for services: 'journal-db'
```
If anyone's having the same issue, what solved it for me was adding:
`version: '3'`
Right at the top of the file.
