### ISSUE TITLE
Better installation docs

### ISSUE THREAD

**Issue by charlesoblack** [inoda/journal#9]
This is kind of a collection of things I had to do to install Journal on a VPS.

- no need for `yarn install`
- skipped installing with `homebrew` (why would I install this on linux if I don't need it? Installed by running the script's commands manually:
  - created a linux user for journal
  - created a postgres user for journal with `sudo -u postgres createuser -D -A -P journal`
  - followed [these](https://github.com/swanson/stringer/blob/master/docs/VPS.md#install-ruby-for-your-stringer-user) instructions to install ruby (2.6.5) and bundler
  - cloned the journal repo and exported the correct ENV variables with the journal user
  - created + migrated the db with `rake`
  - switched to `RAILS_ENV="production"`, which meant also editing the `config/environments/production.rb` file:
    - added `config.hosts << my.host.tld`
    - commented out `config.assets.compile = false`
  - changed port in `config/puma.rb` from 3000 to my own value (I actually think this can be set later when you call `rails`, but I'm not sure)

Then, running `bundle exec rails s` in the folder as the user `journal` should work for launching the application. To make it a systemd service was a little more complex. This is what the service file ended up looking like:

```
[Unit]
Description=InodaJournal
After=network.target

[Service]
Type=simple
User=journal
Group=journal
WorkingDirectory=/home/journal/journal
Environment="JOURNAL_DATABASE_PASSWORD=..."
Environment="CIPHER_KEY=..."
Environtment="SHARING_TOKEN_CIPHER_IV=..."
Environment="RAILS_ENV=production"
Environment="SECRET_KEY_BASE=..."
Environment="PATH=/your/full/journal/user/path"
ExecStart=/home/journal/.rbenv/bin/rbenv exec bundle exec rails s
TimeoutSec=30
RestartSec=15s
Restart=always

[Install]
WantedBy=multi-user.target
```

The one thing that got me with systemd was that initially I was missing `bash` in my `PATH`, so the service was just returning a 127 error code. I found out that `bash` was missing by looking at `journalctl -b` logs.

This basically was installing Journal on a VPS without homebrew (not required) and without Docker, setting it up as a system service. If you want, I can try to write this into a `.md` and make a PR, but I'd just figure I'd write this down first of all so that if anyone ever wants to do the same, they have something to rely on.

**Comment by charlesoblack** [comment]
Looks like my installation still isn't perfect - sharing posts isn't working. It's not super ideal to mention in the install instructions that you need to call some ruby functions to get random bytes in base64 - maybe this could be done in shell instead?

Also, why do you need specifically 32/64 random bytes? Is this a Puma/Ruby/Rails thing, or something set by the application?

**Comment by charlesoblack** [comment]
All this being said... I absolutely love the application. Thank you for putting this out there! I'm definitely going to use it a lot.

**Comment by inoda** [comment]
@charlesoblack Thanks for calling this stuff out! And glad you like the app. The install steps are by no means perfect - there is now a Docker install which might solve some of this pain.

`yarn install` should be removed from install steps now - that was an error on my part.

For the keys - they need to be a specific length. This is required by the `openssl` gem that is used for encrypting contents. They are base64 encoded just so they work as ENV vars.

<img width="322" alt="Screen Shot 2020-01-04 at 3 43 15 PM" src="https://user-images.githubusercontent.com/7588174/71772493-f717d700-2f08-11ea-8390-e94f8c2d393c.png">


As for everything else you called out, I'm not very familiar with setting up systemd and whatnot, would definitely accept a PR with more installation options!
